description: |
  ### Document Name - SHARR-CIS_1.2.0_4.3

  ## What does this document do?
  Removes all access from an EC2 Default Security Group to restrict all traffic.

  ## Input Parameters
  * Finding: (Required) Security Hub finding details JSON
  * AutomationAssumeRole: (Required) The ARN of the role that allows Automation to perform the actions on your behalf.
  
  ## Output Parameters
  * Remediation.Output - Output of remediation runbook.

  ## Documentation Links
  [CIS v1.2.0 4.3](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-cis-controls.html#securityhub-cis-controls-4.3)
  
schemaVersion: '0.3'
assumeRole: '{{ AutomationAssumeRole }}'
outputs:
  - ParseInput.AffectedObject
  - Remediation.Output 
parameters:
  Finding:
    type: StringMap
    description: The input from Step function for finding
  Type:
    type: String
    description: One of three possible types of findings
  RelatedResources:
    type: StringList
    description: List of resources related to current resource
  VPCFlowLogs:
    type: StringList
    description: List of VPC Flow logs related to the current resource
  AccessLogs:
    type: StringList
    description: S3 Access Logs or API Gateway Access logs if available
  AutomationAssumeRole:
    type: String
    description: (Optional) The ARN of the role that allows Automation to perform the actions on your behalf.
    default: ''
    allowedPattern: '^arn:(?:aws|aws-us-gov|aws-cn):iam::\d{12}:role/[\w+=,.@-]+'

mainSteps:
  - name: ParseInput
    action: 'aws:executeScript'
    outputs:
      - Name: GroupId
        Selector: $.Payload.resource_id
        Type: String
      - Name: FindingId
        Selector: $.Payload.finding_id
        Type: String
      - Name: ProductArn
        Selector: $.Payload.product_arn
        Type: String
      - Name: AffectedObject
        Selector: $.Payload.object
        Type: StringMap
    inputs:
      InputPayload:
        Finding: '{{Finding}}'
        parse_id_pattern: '^arn:(?:aws|aws-cn|aws-us-gov):ec2:(?:[a-z]{2}(?:-gov)?-[a-z]+-\d):\d{12}:security-group/(sg-[a-f0-9]{8,17})$'
        expected_control_id: '4.3'
      Runtime: python3.7
      Handler: parse_event
      Script: |-
        %%SCRIPT=cis_parse_input.py%%
    isEnd: false

  - name: CheckForSideEffects
    action: 'aws:branch'
    inputs:
      Choices:
      - NextStep: SideEffects
        Variable: "{{ Type }}"
        StringEquals: "type2"
      - NextStep: Remediation
        Varaible: "{{ Type }}"
        StringEquals: "type3"
      Default:
        Remediation

  - name: SideEffects
    action: 'aws:executeAutomation'
    isEnd: false
    isCritical: True
    onFailure: Abort
    nextStep: Remediation
    inputs:
      DocumentName: SHARR-CreateAndAttachNewSecurityGroup
      RuntimeParamaters:
        GroupId: '{{ ParseInput.GroupId }}'
        Resources: '{{ RelatedResources }}'
        AutomationAssumeRole: 'arn:{{global:AWS_PARTITION}}:iam::{{global:ACCOUNT_ID}}:role/SO0111-CreateAndAttachSecurityGroup_{{global:REGION}}'

  - name: Remediation
    action: 'aws:executeAutomation'
    isEnd: false
    isCritical: True
    onFailure: Abort
    inputs:
      DocumentName: SHARR-RemoveVPCDefaultSecurityGroupRules
      RuntimeParameters:
        GroupId: '{{ ParseInput.GroupId }}'
        AutomationAssumeRole: 'arn:{{global:AWS_PARTITION}}:iam::{{global:ACCOUNT_ID}}:role/SO0111-DisablePublicAccessForSecurityGroup_{{global:REGION}}'

  - name: UpdateFinding
    action: 'aws:executeAwsApi'
    inputs:
      Service: securityhub
      Api: BatchUpdateFindings
      FindingIdentifiers:
      - Id: '{{ParseInput.FindingId}}'
        ProductArn: '{{ParseInput.ProductArn}}'
      Note:
        Text: 'Removed all access to the default security group {{ ParseInput.GroupId }}.'
        UpdatedBy: 'SHARR-CIS_1.2.0_4.3'
      Workflow:
        Status: RESOLVED
    description: Update finding
    isEnd: true
